spring:
  profiles:
    active:
     - dev

---

server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
   profiles: dev
   application:
    name: microservicecloud-Dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password:
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka
  instance:
    instance-id: microservicecloud-dept8002 #修改名字
    prefer-ip-address: true #访问路径显示id地址s
info:
  app.name: test
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}$   #总的工程添加maven-resources插件，
  buid.version: ${project.version}$

---

server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
   profiles: test
   application:
    name: microservicecloud-Dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password:
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka
  instance:
    instance-id: microservicecloud-dept8002 #修改名字
    prefer-ip-address: true #访问路径显示id地址s
info:
  app.name: test
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}$   #总的工程添加maven-resources插件，
  buid.version: ${project.version}$
